name: Sonar qube analysis and version increment

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: run tests
        run: mvn -B verify --file pom.xml -Djasypt.encryptor.password=${{ secrets.JASYPT_PASS }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=bpiatek_linkshortener \
          -Dsonar.organization=bpiatek \
          -Dsonar.host.url=https://sonarcloud.io \

  increment-version:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Increment version
        run: |
          git config user.email my-bot-user@email.com
          git config user.name my-bot-user
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          git add .
          git commit -m "updated version in pom.xml"
          git push

  deploy-to-vps:
    needs: increment-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Package app to jar
        run: mvn -B package --file pom.xml -DskipTests -Djasypt.encryptor.password=${{ secrets.JASYPT_PASS }}

      - name: Stop app and clean up
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.MIKRUS_HOST }}
          user: ${{ secrets.MIKRUS_USERNAME }}
          pass: ${{ secrets.MIKRUS_PASS }}
          port: ${{ secrets.MIKRUS_PORT }}
          command: |
            cd /root/apps/link-app
            ./stop.sh
            ./clean_up.sh

      - name: Copy app to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.MIKRUS_HOST }}
          username: ${{ secrets.MIKRUS_USERNAME }}
          password: ${{ secrets.MIKRUS_PASS }}
          port: ${{ secrets.MIKRUS_PORT }}
          source: "target/link-shortener-*.jar"
          target: "/root/apps/link-app/linkshortener"

      - name: Start application
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.MIKRUS_HOST }}
          user: ${{ secrets.MIKRUS_USERNAME }}
          pass: ${{ secrets.MIKRUS_PASS }}
          port: ${{ secrets.MIKRUS_PORT }}
          command: |
            cd /root/apps/link-app
            ./post_copy.sh
            ./start_silent.sh
